package org.smeup.sys.il.esam.test.dbf;

import org.smeup.sys.il.data.QCharacter;
import org.smeup.sys.il.data.QDecimal;
import org.smeup.sys.il.data.QRecordWrapper;
import org.smeup.sys.il.data.annotation.DataDef;
import org.smeup.sys.il.esam.annotation.Format;

@Format(value = "BRENTIR")
public class BRENTI0F extends QRecordWrapper {
	private static final long serialVersionUID = 1L;
	@DataDef(length = 3)
	public QCharacter eçtrag;
	@DataDef(length = 15)
	public QCharacter eçcrag;
	@DataDef(length = 15)
	public QCharacter eçscen;
	@DataDef(length = 2)
	public QCharacter eçazie;
	@DataDef(length = 10)
	public QCharacter eçidoj;
	@DataDef(precision = 8)
	public QDecimal eçdinv;
	@DataDef(precision = 8)
	public QDecimal eçdfnv;
	@DataDef(length = 3)
	public QCharacter eçgrup;
	@DataDef(length = 35)
	public QCharacter eçnmne;
	@DataDef(length = 15)
	public QCharacter eçncod;
	@DataDef(length = 1)
	public QCharacter eçlive;
	@DataDef(length = 2)
	public QCharacter eçstat;
	@DataDef(length = 35)
	public QCharacter eçrags;
	@DataDef(length = 35)
	public QCharacter eçraga;
	@DataDef(length = 35)
	public QCharacter eçindi;
	@DataDef(length = 35)
	public QCharacter eçinda;
	@DataDef(length = 20)
	public QCharacter eçtele;
	@DataDef(length = 20)
	public QCharacter eçtfax;
	@DataDef(length = 20)
	public QCharacter eçtelx;
	@DataDef(length = 132)
	public QCharacter eçiema;
	@DataDef(length = 20)
	public QCharacter eçpeco;
	@DataDef(length = 6)
	public QCharacter eçcnaz;
	@DataDef(length = 10)
	public QCharacter eçcreg;
	@DataDef(length = 10)
	public QCharacter eçccom;
	@DataDef(length = 35)
	public QCharacter eçloca;
	@DataDef(length = 10)
	public QCharacter eçprov;
	@DataDef(length = 25)
	public QCharacter eçnazi;
	@DataDef(length = 10)
	public QCharacter eçcapa;
	@DataDef(length = 3)
	public QCharacter eçzona;
	@DataDef(length = 3)
	public QCharacter eçling;
	@DataDef(length = 4)
	public QCharacter eçvalu;
	@DataDef(length = 3)
	public QCharacter eçtsog;
	@DataDef(length = 30)
	public QCharacter eçcpai;
	@DataDef(length = 20)
	public QCharacter eçcofi;
	@DataDef(length = 30)
	public QCharacter eçcpae;
	@DataDef(length = 6)
	public QCharacter eçcta1;
	@DataDef(length = 6)
	public QCharacter eçcta2;
	@DataDef(length = 6)
	public QCharacter eçcta3;
	@DataDef(precision = 8)
	public QDecimal eçdves;
	@DataDef(length = 15)
	public QCharacter eçcdin;
	@DataDef(precision = 8)
	public QDecimal eçddin;
	@DataDef(length = 3)
	public QCharacter eçtnom;
	@DataDef(length = 15)
	public QCharacter eçcnom;
	@DataDef(length = 3)
	public QCharacter eçtspe;
	@DataDef(length = 15)
	public QCharacter eçcspe;
	@DataDef(length = 3)
	public QCharacter eçtcon;
	@DataDef(length = 15)
	public QCharacter eçccon;
	@DataDef(length = 3)
	public QCharacter eçtinc;
	@DataDef(length = 15)
	public QCharacter eçcinc;
	@DataDef(length = 3)
	public QCharacter eçtprz;
	@DataDef(length = 15)
	public QCharacter eçcprz;
	@DataDef(length = 3)
	public QCharacter eçtcrr;
	@DataDef(length = 15)
	public QCharacter eçccrr;
	@DataDef(length = 3)
	public QCharacter eçtvet;
	@DataDef(length = 15)
	public QCharacter eçcvet;
	@DataDef(length = 15)
	public QCharacter eçcaco;
	@DataDef(length = 3)
	public QCharacter eçcacr;
	@DataDef(length = 4)
	public QCharacter eçclab;
	@DataDef(length = 4)
	public QCharacter eçclav;
	@DataDef(length = 6)
	public QCharacter eçcsme;
	@DataDef(length = 3)
	public QCharacter eçcons;
	@DataDef(length = 3)
	public QCharacter eçsped;
	@DataDef(length = 3)
	public QCharacter eçimba;
	@DataDef(length = 5)
	public QCharacter eçcaus;
	@DataDef(length = 2)
	public QCharacter eçgchi;
	@DataDef(length = 2)
	public QCharacter eçgcon;
	@DataDef(length = 2)
	public QCharacter eçgcol;
	@DataDef(length = 3)
	public QCharacter eçagen;
	@DataDef(precision = 6, scale = 3)
	public QDecimal eçperp;
	@DataDef(length = 3)
	public QCharacter eçage1;
	@DataDef(precision = 6, scale = 3)
	public QDecimal eçper1;
	@DataDef(length = 5)
	public QCharacter eçcrcp;
	@DataDef(length = 3)
	public QCharacter eçcopa;
	@DataDef(length = 3)
	public QCharacter eçcsp1;
	@DataDef(length = 3)
	public QCharacter eçcsp2;
	@DataDef(length = 3)
	public QCharacter eçcsp3;
	@DataDef(length = 3)
	public QCharacter eçcsp4;
	@DataDef(length = 3)
	public QCharacter eçcsp5;
	@DataDef(length = 3)
	public QCharacter eçlist;
	@DataDef(precision = 4, scale = 2)
	public QDecimal eçscon;
	@DataDef(length = 2)
	public QCharacter eçprio;
	@DataDef(precision = 21, scale = 6)
	public QDecimal eçfido;
	@DataDef(length = 15)
	public QCharacter eçbanc;
	@DataDef(length = 15)
	public QCharacter eçccor;
	@DataDef(length = 15)
	public QCharacter eçcba2;
	@DataDef(length = 35)
	public QCharacter eçiban;
	@DataDef(length = 15)
	public QCharacter eçswif;
	@DataDef(length = 15)
	public QCharacter eçcba3;
	@DataDef(precision = 8)
	public QDecimal eçdtie;
	@DataDef(precision = 8)
	public QDecimal eçdt01;
	@DataDef(precision = 8)
	public QDecimal eçdt02;
	@DataDef(precision = 8)
	public QDecimal eçdt03;
	@DataDef(precision = 8)
	public QDecimal eçdt04;
	@DataDef(precision = 8)
	public QDecimal eçdt05;
	@DataDef(precision = 8)
	public QDecimal eçdt06;
	@DataDef(precision = 8)
	public QDecimal eçdt07;
	@DataDef(precision = 8)
	public QDecimal eçdt08;
	@DataDef(precision = 8)
	public QDecimal eçdt09;
	@DataDef(precision = 8)
	public QDecimal eçdt10;
	@DataDef(length = 15)
	public QCharacter eçcod1;
	@DataDef(length = 15)
	public QCharacter eçcod2;
	@DataDef(length = 15)
	public QCharacter eçcod3;
	@DataDef(length = 15)
	public QCharacter eçcod4;
	@DataDef(length = 15)
	public QCharacter eçcod5;
	@DataDef(length = 15)
	public QCharacter eçcod6;
	@DataDef(length = 15)
	public QCharacter eçcod7;
	@DataDef(length = 15)
	public QCharacter eçcod8;
	@DataDef(length = 15)
	public QCharacter eçcod9;
	@DataDef(length = 15)
	public QCharacter eçcod0;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum1;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum2;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum3;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum4;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum5;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum6;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum7;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum8;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum9;
	@DataDef(precision = 15, scale = 5)
	public QDecimal eçnum0;
	@DataDef(length = 1)
	public QCharacter eçfl01;
	@DataDef(length = 1)
	public QCharacter eçfl02;
	@DataDef(length = 1)
	public QCharacter eçfl03;
	@DataDef(length = 1)
	public QCharacter eçfl04;
	@DataDef(length = 1)
	public QCharacter eçfl05;
	@DataDef(length = 1)
	public QCharacter eçfl06;
	@DataDef(length = 1)
	public QCharacter eçfl07;
	@DataDef(length = 1)
	public QCharacter eçfl08;
	@DataDef(length = 1)
	public QCharacter eçfl09;
	@DataDef(length = 1)
	public QCharacter eçfl10;
	@DataDef(length = 1)
	public QCharacter eçfl11;
	@DataDef(length = 1)
	public QCharacter eçfl12;
	@DataDef(length = 1)
	public QCharacter eçfl13;
	@DataDef(length = 1)
	public QCharacter eçfl14;
	@DataDef(length = 1)
	public QCharacter eçfl15;
	@DataDef(length = 1)
	public QCharacter eçfl16;
	@DataDef(length = 1)
	public QCharacter eçfl17;
	@DataDef(length = 1)
	public QCharacter eçfl18;
	@DataDef(length = 1)
	public QCharacter eçfl19;
	@DataDef(length = 1)
	public QCharacter eçfl20;
	@DataDef(length = 1)
	public QCharacter eçfl21;
	@DataDef(length = 1)
	public QCharacter eçfl22;
	@DataDef(length = 1)
	public QCharacter eçfl23;
	@DataDef(length = 1)
	public QCharacter eçfl24;
	@DataDef(length = 1)
	public QCharacter eçfl25;
	@DataDef(length = 1)
	public QCharacter eçfl26;
	@DataDef(length = 1)
	public QCharacter eçfl27;
	@DataDef(length = 1)
	public QCharacter eçfl28;
	@DataDef(length = 1)
	public QCharacter eçfl29;
	@DataDef(length = 1)
	public QCharacter eçfl30;
	@DataDef(length = 1)
	public QCharacter eçfl31;
	@DataDef(length = 1)
	public QCharacter eçfl32;
	@DataDef(length = 1)
	public QCharacter eçfl33;
	@DataDef(length = 1)
	public QCharacter eçfl34;
	@DataDef(length = 1)
	public QCharacter eçfl35;
	@DataDef(length = 1)
	public QCharacter eçfl36;
	@DataDef(length = 1)
	public QCharacter eçfl37;
	@DataDef(length = 1)
	public QCharacter eçfl38;
	@DataDef(length = 1)
	public QCharacter eçfl39;
	@DataDef(length = 1)
	public QCharacter eçfl40;
	@DataDef(precision = 6)
	public QDecimal eçorin;
	@DataDef(precision = 8)
	public QDecimal eçdtin;
	@DataDef(length = 10)
	public QCharacter eçusin;
	@DataDef(precision = 6)
	public QDecimal eçorag;
	@DataDef(precision = 8)
	public QDecimal eçdtag;
	@DataDef(length = 10)
	public QCharacter eçusag;
}
