<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lock" nsURI="http://www.smeup.org/asup/il/lock" nsPrefix="il-lock">
  <eClassifiers xsi:type="ecore:EClass" name="LockManager" abstract="true" interface="true">
    <eOperations name="getLocker">
      <eGenericType eClassifier="#//ObjectLocker">
        <eTypeArguments eTypeParameter="#//LockManager/getLocker/N"/>
      </eGenericType>
      <eTypeParameters name="N">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="context" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/Context"/>
      <eParameters name="object">
        <eGenericType eTypeParameter="#//LockManager/getLocker/N"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LockType">
    <eLiterals name="Read" value="10" literal="READ"/>
    <eLiterals name="Write" value="20" literal="WRITE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectLocker" abstract="true" interface="true">
    <eTypeParameters name="N">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eOperations name="lock">
      <eParameters name="lockType" lowerBound="1" eType="#//LockType"/>
    </eOperations>
    <eOperations name="tryLock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eParameters name="lockType" lowerBound="1" eType="#//LockType"/>
    </eOperations>
    <eOperations name="unlock">
      <eParameters name="lockType" lowerBound="1" eType="#//LockType"/>
    </eOperations>
    <eOperations name="isLocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="lockType" lowerBound="1" eType="#//LockType"/>
    </eOperations>
    <eOperations name="getObjectURI" lowerBound="1" eType="ecore:EDataType ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaURI"/>
  </eClassifiers>
</ecore:EPackage>
