<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="repo" nsURI="http://www.smeup.org/asup/rt/repo" nsPrefix="rt-repo">
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryManager" abstract="true" interface="true">
    <eOperations name="checkUpdates">
      <eParameters name="application" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.rt.core/model/rt-core.ecore#//Application"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
