<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="memo" nsURI="http://www.smeup.org/asup/il/memo" nsPrefix="il-memo">
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true" interface="true"
      eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Nameable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceDef" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceEvent" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eOperations name="getContextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
    <eOperations name="getEventType" lowerBound="1" eType="#//ResourceEventType"/>
    <eOperations name="getNewName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getOldName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getResource" lowerBound="1" eType="#//Resource"/>
    <eOperations name="getSource" lowerBound="1">
      <eGenericType eTypeParameter="#//ResourceEvent/T"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResourceEventType">
    <eLiterals name="PreSave" value="10" literal="PRESAVE"/>
    <eLiterals name="PostSave" value="20" literal="POSTSAVE"/>
    <eLiterals name="PreDelete" value="60" literal="PREDLT"/>
    <eLiterals name="PostDelete" value="70" literal="POSTDLT"/>
    <eLiterals name="PreRename" value="80" literal="PRERNM"/>
    <eLiterals name="PostRename" value="90" literal="POSTRNM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceHandler" abstract="true" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextProvider" lowerBound="1"
        eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"
        transient="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceListener" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eOperations name="handleEvent">
      <eParameters name="event" lowerBound="1">
        <eGenericType eClassifier="#//ResourceEvent">
          <eTypeArguments eTypeParameter="#//ResourceListener/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceManager" abstract="true" interface="true"
      eSuperTypes="#//ResourceProvider">
    <eOperations name="createResource" lowerBound="1">
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="resource" lowerBound="1" eType="#//ResourceDef"/>
      <eParameters name="replace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="registerListener">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceManager/registerListener/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="listener" lowerBound="1">
        <eGenericType eClassifier="#//ResourceListener">
          <eTypeArguments eTypeParameter="#//ResourceManager/registerListener/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="registerProvider">
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceManager/registerProvider/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="provider" lowerBound="1" eType="#//ResourceProvider"/>
    </eOperations>
    <eOperations name="getResourceReader">
      <eGenericType eClassifier="#//ResourceReader">
        <eTypeArguments eTypeParameter="#//ResourceManager/getResourceReader/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceManager/getResourceReader/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="scope" eType="#//Scope"/>
    </eOperations>
    <eOperations name="getResourceReader">
      <eGenericType eClassifier="#//ResourceReader">
        <eTypeArguments eTypeParameter="#//ResourceManager/getResourceReader.1/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceManager/getResourceReader.1/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="scope" eType="#//Scope"/>
      <eParameters name="resource" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getResourceWriter">
      <eGenericType eClassifier="#//ResourceWriter">
        <eTypeArguments eTypeParameter="#//ResourceManager/getResourceWriter/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceManager/getResourceWriter/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="scope" eType="#//Scope"/>
    </eOperations>
    <eOperations name="getResourceWriter">
      <eGenericType eClassifier="#//ResourceWriter">
        <eTypeArguments eTypeParameter="#//ResourceManager/getResourceWriter.1/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceManager/getResourceWriter.1/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="scope" eType="#//Scope"/>
      <eParameters name="resource" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceNotifier">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eOperations name="fireEvent">
      <eParameters name="event" lowerBound="1">
        <eGenericType eClassifier="#//ResourceEvent">
          <eTypeArguments eTypeParameter="#//ResourceNotifier/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getListeners" upperBound="-1">
      <eGenericType eClassifier="#//ResourceListener">
        <eTypeArguments eTypeParameter="#//ResourceNotifier/T"/>
      </eGenericType>
    </eOperations>
    <eOperations name="registerListener">
      <eParameters name="listener" lowerBound="1">
        <eGenericType eClassifier="#//ResourceListener">
          <eTypeArguments eTypeParameter="#//ResourceNotifier/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceProvider" abstract="true" interface="true">
    <eOperations name="getResourceReader">
      <eGenericType eClassifier="#//ResourceReader">
        <eTypeArguments eTypeParameter="#//ResourceProvider/getResourceReader/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceProvider/getResourceReader/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="resource" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getResourceReader">
      <eGenericType eClassifier="#//ResourceReader">
        <eTypeArguments eTypeParameter="#//ResourceProvider/getResourceReader.1/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceProvider/getResourceReader.1/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="resources" lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getResourceWriter">
      <eGenericType eClassifier="#//ResourceWriter">
        <eTypeArguments eTypeParameter="#//ResourceProvider/getResourceWriter/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
      </eTypeParameters>
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ResourceProvider/getResourceWriter/T"/>
        </eGenericType>
      </eParameters>
      <eParameters name="resource" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceReader" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eOperations name="exists" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="find">
      <eGenericType eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectIterator">
        <eTypeArguments eTypeParameter="#//ResourceReader/T"/>
      </eGenericType>
      <eParameters name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findByExpression">
      <eGenericType eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectIterator">
        <eTypeArguments eTypeParameter="#//ResourceReader/T"/>
      </eGenericType>
      <eParameters name="filter" eType="ecore:EClass ../../org.smeup.sys.il.expr/model/il-expr.ecore#//PredicateExpression"/>
    </eOperations>
    <eOperations name="lookup">
      <eGenericType eTypeParameter="#//ResourceReader/T"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notifier">
      <eGenericType eClassifier="#//ResourceNotifier">
        <eTypeArguments eTypeParameter="#//ResourceReader/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//ResourceHandler">
      <eTypeArguments eTypeParameter="#//ResourceReader/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceWriter" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable"/>
    </eTypeParameters>
    <eOperations name="copy" lowerBound="1">
      <eGenericType eTypeParameter="#//ResourceWriter/T"/>
      <eParameters name="object" lowerBound="1">
        <eGenericType eTypeParameter="#//ResourceWriter/T"/>
      </eParameters>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="delete">
      <eParameters name="object" lowerBound="1">
        <eGenericType eTypeParameter="#//ResourceWriter/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="getResource" lowerBound="1" eType="#//Resource"/>
    <eOperations name="save">
      <eParameters name="object" lowerBound="1">
        <eGenericType eTypeParameter="#//ResourceWriter/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="save">
      <eParameters name="object" lowerBound="1">
        <eGenericType eTypeParameter="#//ResourceWriter/T"/>
      </eParameters>
      <eParameters name="replace" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="rename">
      <eParameters name="object" lowerBound="1">
        <eGenericType eTypeParameter="#//ResourceWriter/T"/>
      </eParameters>
      <eParameters name="newName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//ResourceReader">
      <eTypeArguments eTypeParameter="#//ResourceWriter/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Scope">
    <eLiterals name="All" value="10" literal="*ALL"/>
    <eLiterals name="LibraryList" value="20" literal="*LIBL"/>
    <eLiterals name="CurrentLibrary" value="30" literal="*CURLIB"/>
    <eLiterals name="UserLibraryList" value="40" literal="*USRLIBL"/>
    <eLiterals name="AllUser" value="50" literal="*ALLUSR"/>
    <eLiterals name="SystemLibrary" value="90" literal="*SYSLIB"/>
    <eLiterals name="Other" value="99" literal="*OTHER"/>
  </eClassifiers>
</ecore:EPackage>
