<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://www.smeup.org/asup/il/core" nsPrefix="il-core">
  <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true" interface="true">
    <eOperations name="getName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaSerializable">
    <eOperations name="qURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectAdapter" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectContainer" abstract="true" eSuperTypes="#//Object">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Object"/>
    </eTypeParameters>
    <eOperations name="lookupByName" lowerBound="1">
      <eGenericType eTypeParameter="#//ObjectContainer/T"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//ObjectContainer/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIterator" abstract="true" interface="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Object"/>
    </eTypeParameters>
    <eOperations name="close"/>
    <eOperations name="hasNext" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="next" lowerBound="1">
      <eGenericType eTypeParameter="#//ObjectIterator/T"/>
    </eOperations>
    <eOperations name="remove"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaIterator">
      <eTypeArguments eTypeParameter="#//ObjectIterator/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaCloseable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNameable" eSuperTypes="#//Object #//Nameable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRegistry" abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eOperations name="lookup" lowerBound="1">
      <eGenericType eTypeParameter="#//ObjectRegistry/T"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="list" lowerBound="1" upperBound="-1">
      <eGenericType eTypeParameter="#//ObjectRegistry/T"/>
    </eOperations>
    <eOperations name="lookupByVendorVersion" lowerBound="1">
      <eGenericType eTypeParameter="#//ObjectRegistry/T"/>
      <eParameters name="vendor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="version" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRegistryFactory" abstract="true"
      interface="true">
    <eOperations name="createObjectRegistry" lowerBound="1">
      <eGenericType eClassifier="#//ObjectRegistry">
        <eTypeArguments eTypeParameter="#//ObjectRegistryFactory/createObjectRegistry/T"/>
      </eGenericType>
      <eTypeParameters name="T"/>
      <eParameters name="klass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//ObjectRegistryFactory/createObjectRegistry/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectRegistryKey" eSuperTypes="#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thread" abstract="true" interface="true"
      eSuperTypes="#//Object">
    <eOperations name="checkRunnable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getJavaThread" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaThread"/>
    <eOperations name="getThreadID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="il-data" references="il-data.ecore#//def/DecimalDef">
        <details key="precision" value="10"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getThreadName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="il-data.ecore#//def/CharacterDef">
        <details key="length" value="96"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getThreadPriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="il-data" references="il-data.ecore#//def/DecimalDef">
        <details key="precision" value="10"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getThreadCPUUsage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="il-data" references="il-data.ecore#//def/DecimalDef">
        <details key="precision" value="10"/>
        <details key="scale" value="2"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getThreadStatus" eType="#//ThreadStatus">
      <eAnnotations source="il-data" references="il-data.ecore#//def/CharacterDef">
        <details key="length" value="12"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isInterrupted" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="il-data" references="il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isNative" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="il-data" references="il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isSuspended" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="il-data" references="il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isThreadDaemon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="il-data" references="il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreadManager" abstract="true" interface="true">
    <eOperations name="createThread" eType="#//Thread">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="runnable" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaRunnable"/>
    </eOperations>
    <eOperations name="createThread" eType="#//Thread">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="runnable" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaRunnable"/>
      <eParameters name="daemon" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="currentThread" lowerBound="1" eType="#//Thread"/>
    <eOperations name="listThreads" upperBound="-1" eType="#//Thread"/>
    <eOperations name="lookupThread" eType="#//Thread">
      <eParameters name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="lookupThread" eType="#//Thread">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="release">
      <eParameters name="thread" lowerBound="1" eType="#//Thread"/>
    </eOperations>
    <eOperations name="start">
      <eParameters name="thread" lowerBound="1" eType="#//Thread"/>
    </eOperations>
    <eOperations name="stop">
      <eParameters name="thread" lowerBound="1" eType="#//Thread"/>
    </eOperations>
    <eOperations name="suspend">
      <eParameters name="thread" lowerBound="1" eType="#//Thread"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//util/Singleton">
      <eTypeArguments eClassifier="#//ThreadManager"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ThreadStatus">
    <eLiterals name="New" value="10" literal="NEW"/>
    <eLiterals name="Runnable" value="20" literal="RUN"/>
    <eLiterals name="Blocked" value="30" literal="BLOCK"/>
    <eLiterals name="Waiting" value="40" literal="WAIT"/>
    <eLiterals name="TimedWaiting" value="50" literal="TIME_WAIT"/>
    <eLiterals name="Terminated" value="60" literal="END"/>
  </eClassifiers>
  <eSubpackages name="ctx" nsURI="http://www.smeup.org/asup/il/core/ctx" nsPrefix="il-core-ctx">
    <eClassifiers xsi:type="ecore:EClass" name="AdapterFactory" abstract="true" interface="true">
      <eOperations name="getAdapter">
        <eGenericType eTypeParameter="#//ctx/AdapterFactory/getAdapter/T"/>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eParameters name="context" lowerBound="1" eType="#//ctx/Context"/>
        <eParameters name="adaptable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="adapterType" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/AdapterFactory/getAdapter/T"/>
          </eGenericType>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Capability" abstract="true" interface="true"
        eSuperTypes="#//Object">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//Object"/>
      </eTypeParameters>
      <eOperations name="getObjectURI" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rights" upperBound="-1"
          eType="#//ctx/CapabilityRight"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Context" abstract="true">
      <eOperations name="close" lowerBound="1"/>
      <eOperations name="createChildContext" lowerBound="1" eType="#//ctx/Context">
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="createChildContext" lowerBound="1" eType="#//ctx/Context">
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="injectionStrategy" lowerBound="1" eType="#//ctx/ContextInjectionStrategy"/>
      </eOperations>
      <eOperations name="createChildContext" lowerBound="1" eType="#//ctx/Context">
        <eParameters name="contextDescription" lowerBound="1" eType="#//ctx/ContextDescription"/>
        <eParameters name="injectionStrategy" lowerBound="1" eType="#//ctx/ContextInjectionStrategy"/>
      </eOperations>
      <eOperations name="get" lowerBound="1">
        <eGenericType eTypeParameter="#//ctx/Context/get/T"/>
        <eTypeParameters name="T"/>
        <eParameters name="clazz" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/Context/get/T"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="getAdapter">
        <eGenericType eTypeParameter="#//ctx/Context/getAdapter/T"/>
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eParameters name="adaptable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="adapter" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/Context/getAdapter/T"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="getContextDescription" lowerBound="1" eType="#//ctx/ContextDescription"/>
      <eOperations name="getID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="inject">
        <eParameters name="object" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="isClosed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="loadClass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
        <eParameters name="address" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="loadClassByName" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
        <eParameters name="className" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="invoke">
        <eTypeParameters name="A">
          <eBounds eClassifier="ecore:EDataType ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaAnnotation"/>
        </eTypeParameters>
        <eParameters name="object" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="qualifier" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/Context/invoke/A"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="make" lowerBound="1">
        <eGenericType eTypeParameter="#//ctx/Context/make/T"/>
        <eTypeParameters name="T"/>
        <eParameters name="klass" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/Context/make/T"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="registerAdapterFactory">
        <eTypeParameters name="T">
          <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eTypeParameters>
        <eParameters name="factory" lowerBound="1" eType="#//ctx/AdapterFactory"/>
        <eParameters name="adapterType" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/Context/registerAdapterFactory/T"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="resolveAlias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="resolveAliases" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="values" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="set" lowerBound="1">
        <eTypeParameters name="T"/>
        <eParameters name="klass" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//ctx/Context/set/T"/>
          </eGenericType>
        </eParameters>
        <eParameters name="object" lowerBound="1">
          <eGenericType eTypeParameter="#//ctx/Context/set/T"/>
        </eParameters>
      </eOperations>
      <eOperations name="set" lowerBound="1">
        <eTypeParameters name="T"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="object" lowerBound="1">
          <eGenericType eTypeParameter="#//ctx/Context/set.1/T"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContextDescription" abstract="true"
        interface="true">
      <eOperations name="getCurrentLibrary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getLibraryPath" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSystemLibrary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getTemporaryLibrary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ContextInjectionStrategy">
      <eLiterals name="Local" value="10" literal="LOCAL"/>
      <eLiterals name="Remote" value="20" literal="REMOTE"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContextProvider" abstract="true" interface="true">
      <eOperations name="getContext" lowerBound="1" eType="#//ctx/Context"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identity" abstract="true" interface="true"
        eSuperTypes="#//Object">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//Object"/>
      </eTypeParameters>
      <eOperations name="getJavaPrincipal" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaPrincipal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CapabilityRight">
      <eLiterals name="Read" value="10" literal="READ"/>
      <eLiterals name="Write" value="20" literal="WRITE"/>
      <eLiterals name="Execute" value="30" literal="EXEC"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="meta" nsURI="http://www.smeup.org/asup/il/core/meta" nsPrefix="il-core-meta">
    <eClassifiers xsi:type="ecore:EClass" name="Cardinality" eSuperTypes="#//Object">
      <eOperations name="isMandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isMultiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Default" eSuperTypes="#//Object">
      <eOperations name="clear"/>
      <eOperations name="isEmpty" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Facet" abstract="true" eSuperTypes="#//Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="Frame" abstract="true" interface="true"
        eSuperTypes="#//ObjectNameable">
      <eTypeParameters name="O">
        <eBounds eClassifier="#//Object"/>
      </eTypeParameters>
      <eOperations name="ako">
        <eGenericType eClassifier="#//meta/Frame">
          <eTypeArguments/>
        </eGenericType>
      </eOperations>
      <eOperations name="getSlot" lowerBound="1" eType="#//meta/Slot">
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getSlots" upperBound="-1" eType="#//meta/Slot"/>
      <eOperations name="getValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eParameters name="object" lowerBound="1" eType="#//Object"/>
        <eParameters name="slot" lowerBound="1" eType="#//meta/Slot"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FrameManager" abstract="true" interface="true">
      <eOperations name="getFrame" lowerBound="1">
        <eGenericType eClassifier="#//meta/Frame">
          <eTypeArguments eTypeParameter="#//meta/FrameManager/getFrame/O"/>
        </eGenericType>
        <eTypeParameters name="O">
          <eBounds eClassifier="#//Object"/>
        </eTypeParameters>
        <eParameters name="object" lowerBound="1">
          <eGenericType eTypeParameter="#//meta/FrameManager/getFrame/O"/>
        </eParameters>
      </eOperations>
      <eOperations name="getFrame" lowerBound="1">
        <eGenericType eClassifier="#//meta/Frame">
          <eTypeArguments/>
        </eGenericType>
        <eParameters name="eClass" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      </eOperations>
      <eOperations name="createObject" lowerBound="1">
        <eGenericType eTypeParameter="#//meta/FrameManager/createObject/O"/>
        <eTypeParameters name="O">
          <eBounds eClassifier="#//Object"/>
        </eTypeParameters>
        <eParameters name="frame" lowerBound="1">
          <eGenericType eClassifier="#//meta/Frame">
            <eTypeArguments eTypeParameter="#//meta/FrameManager/createObject/O"/>
          </eGenericType>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Slot" abstract="true" interface="true"
        eSuperTypes="#//Nameable">
      <eOperations name="getCardinality" eType="#//meta/Cardinality"/>
      <eOperations name="getDefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eOperations name="isTransient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isVolatile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getValue" eType="#//Object">
        <eParameters name="nsPrefix" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="out" nsURI="http://www.smeup.org/asup/il/core/out" nsPrefix="il-core-out">
    <eClassifiers xsi:type="ecore:EClass" name="ObjectWriter" abstract="true" interface="true">
      <eOperations name="flush"/>
      <eOperations name="initialize"/>
      <eOperations name="write" eExceptions="ecore:EDataType ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaIOException">
        <eParameters name="object" lowerBound="1" eType="#//Object"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectWriterFactory" abstract="true"
        interface="true">
      <eOperations name="createObjectWriter" lowerBound="1" eType="#//out/ObjectWriter">
        <eParameters name="context" lowerBound="1" eType="#//ctx/Context"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectWriterFactoryRegistry" abstract="true"
        interface="true">
      <eGenericSuperTypes eClassifier="#//ObjectRegistry">
        <eTypeArguments eClassifier="#//out/ObjectWriterFactory"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutputManager" abstract="true" interface="true">
      <eOperations name="getDefaultWriter" lowerBound="1" eType="#//out/ObjectWriter">
        <eParameters name="context" lowerBound="1" eType="#//ctx/Context"/>
      </eOperations>
      <eOperations name="getObjectWriter" lowerBound="1" eType="#//out/ObjectWriter">
        <eParameters name="context" lowerBound="1" eType="#//ctx/Context"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="registerWriter">
        <eParameters name="context" lowerBound="1" eType="#//ctx/Context"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="writer" lowerBound="1" eType="#//out/ObjectWriter"/>
      </eOperations>
      <eOperations name="setDefaultWriter">
        <eParameters name="context" lowerBound="1" eType="#//ctx/Context"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="term" nsURI="http://www.smeup.org/asup/il/core/term" nsPrefix="il-core-term">
    <eClassifiers xsi:type="ecore:EClass" name="NamedNode" abstract="true" eSuperTypes="#//term/Node #//Nameable"/>
    <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
      <eOperations name="getParent" lowerBound="1" eType="#//term/Node"/>
      <eOperations name="isChild" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getFacet">
        <eGenericType eTypeParameter="#//term/Node/getFacet/F"/>
        <eTypeParameters name="F">
          <eBounds eClassifier="#//meta/Facet"/>
        </eTypeParameters>
        <eParameters name="klass" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//term/Node/getFacet/F"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
          eType="#//meta/Facet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Term" abstract="true" interface="true"
        eSuperTypes="#//term/NamedNode">
      <eOperations name="getText" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getURI" eType="ecore:EDataType ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaURI"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TermContainer" abstract="true" interface="true">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//term/Term"/>
      </eTypeParameters>
      <eOperations name="getTerms" upperBound="-1">
        <eGenericType eTypeParameter="#//term/TermContainer/T"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
