@echo off

if ""=="%1"  (
    echo Usage: %0 dbName
    goto FINE
)

createdb "" %1

db2 -x  CONNECT TO %1
db2 -x  GRANT DBADM, CREATETAB, BINDADD, CONNECT, CREATE_NOT_FENCED, IMPLICIT_SCHEMA, LOAD ON DATABASE TO USER ASUP
db2 -x  UPDATE DATABASE CONFIGURATION FOR %1 USING LOGFILSIZ 1000
db2 -x  UPDATE DATABASE CONFIGURATION FOR %1 USING LOGPRIMARY 16
db2 -x  UPDATE DATABASE CONFIGURATION FOR %1 USING LOGSECOND 240

echo Database %1 created

:FINE