<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="type" nsURI="http://www.smeup.org/asup/os/type" nsPrefix="os-type">
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//TypedObject">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//TypedObject"/>
    </eTypeParameters>
    <eOperations name="getTypedClass">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments eTypeParameter="#//Type/T"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typedClassName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRegistry" abstract="true" interface="true">
    <eOperations name="lookup" lowerBound="1">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="typedClass" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="lookup" lowerBound="1">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="list" lowerBound="1" upperBound="-1">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedContainer" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//TypedObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectContainer">
      <eTypeArguments eTypeParameter="#//TypedContainer/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedObject" abstract="true" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable">
    <eOperations name="getAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="5"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLibrary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="application" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//meta/Facet"
        containment="true">
      <eAnnotations source="dk-core" references="../../org.smeup.sys.dk.core/model/dk.core.ecore#//Comment">
        <details key="text" value="Per ora metto i facets sul typedObject, ma non ne sono tanto sicuro&#xA;Almeno però posso annotare gli oggetti tipizzati"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="50"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creationInfo" eType="ecore:EClass ../../org.smeup.sys.os.core/model/os-core.ecore#//CreationInfo"
        containment="true">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="30"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedRef" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//TypedObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attributo dell'oggetto.&#xA;&#xA;Ogni oggetto di tip QObject prevede una ulteriore specificazione di tipo dfinita tramite attributo.&#xA;L'attributo non partecipa all'ereditarieta' dell'oggetto pur influenzandono comportamenti e proprieta'."/>
      </eAnnotations>
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
        <details key="length" value="10"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeContainer">
    <eGenericSuperTypes eClassifier="#//TypedContainer">
      <eTypeArguments eClassifier="#//Type">
        <eTypeArguments/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
