<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esam" nsURI="http://www.smeup.org/asup/il/esam" nsPrefix="il-esam">
  <eClassifiers xsi:type="ecore:EClass" name="AccessFactory" abstract="true" interface="true">
    <eOperations name="createKeySequencedDataSet" lowerBound="1">
      <eGenericType eClassifier="#//KSDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet/R"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="createKeySequencedDataSet" lowerBound="1">
      <eGenericType eClassifier="#//KSDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.1/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.1/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
    </eOperations>
    <eOperations name="createKeySequencedDataSet" lowerBound="1">
      <eGenericType eClassifier="#//KSDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.2/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.2/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="createKeySequencedDataSet" lowerBound="1">
      <eGenericType eClassifier="#//KSDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.3/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.3/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="infoStruct" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
    </eOperations>
    <eOperations name="createKeySequencedDataSet" lowerBound="1">
      <eGenericType eClassifier="#//KSDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.4/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createKeySequencedDataSet.4/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="record" lowerBound="1">
        <eGenericType eTypeParameter="#//AccessFactory/createKeySequencedDataSet.4/R"/>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="infoStruct" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
    </eOperations>
    <eOperations name="createRelativeRecordDataSet" lowerBound="1">
      <eGenericType eClassifier="#//RRDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet/R"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="createRelativeRecordDataSet" lowerBound="1">
      <eGenericType eClassifier="#//RRDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.1/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.1/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
    </eOperations>
    <eOperations name="createRelativeRecordDataSet" lowerBound="1">
      <eGenericType eClassifier="#//RRDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.2/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.2/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="createRelativeRecordDataSet" lowerBound="1">
      <eGenericType eClassifier="#//RRDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.3/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.3/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="infoStruct" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
    </eOperations>
    <eOperations name="createRelativeRecordDataSet" lowerBound="1">
      <eGenericType eClassifier="#//RRDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.4/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.4/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="record" lowerBound="1">
        <eGenericType eTypeParameter="#//AccessFactory/createRelativeRecordDataSet.4/R"/>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="infoStruct" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
    </eOperations>
    <eOperations name="createSourceMemberDataSet" lowerBound="1">
      <eGenericType eClassifier="#//SMDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet/R"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="createSourceMemberDataSet" lowerBound="1">
      <eGenericType eClassifier="#//SMDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.1/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.1/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
    </eOperations>
    <eOperations name="createSourceMemberDataSet" lowerBound="1">
      <eGenericType eClassifier="#//SMDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.2/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.2/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="createSourceMemberDataSet" lowerBound="1">
      <eGenericType eClassifier="#//SMDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.3/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.3/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="infoStruct" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
    </eOperations>
    <eOperations name="createSourceMemberDataSet" lowerBound="1">
      <eGenericType eClassifier="#//SMDataSet">
        <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.4/R"/>
      </eGenericType>
      <eTypeParameters name="R">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
      </eTypeParameters>
      <eParameters name="wrapper" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//AccessFactory/createSourceMemberDataSet.4/R"/>
        </eGenericType>
      </eParameters>
      <eParameters name="record" lowerBound="1">
        <eGenericType eTypeParameter="#//AccessFactory/createSourceMemberDataSet.4/R"/>
      </eParameters>
      <eParameters name="accessMode" eType="#//AccessMode"/>
      <eParameters name="userOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="infoStruct" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessManager" abstract="true" interface="true">
    <eOperations name="createFactory" lowerBound="1" eType="#//AccessFactory">
      <eParameters name="contextProvider" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider"/>
      <eParameters name="dataContext" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataContext"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessMode">
    <eLiterals name="Input" value="10" literal="I"/>
    <eLiterals name="Output" value="20" literal="O"/>
    <eLiterals name="Update" value="30" literal="U"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSet" abstract="true" interface="true">
    <eTypeParameters name="R">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
    </eTypeParameters>
    <eOperations name="clear"/>
    <eOperations name="close"/>
    <eOperations name="close">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="delete"/>
    <eOperations name="delete">
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="delete">
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="isEndOfData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isEqual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isFound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="onError" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="open"/>
    <eOperations name="open">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="read" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="read" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="read" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="read" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="read" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="read" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="readp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="readp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="readp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="unlock"/>
    <eOperations name="unlock">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="update"/>
    <eOperations name="update">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="write"/>
    <eOperations name="write">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="get" lowerBound="1">
      <eGenericType eTypeParameter="#//DataSet/R"/>
    </eOperations>
    <eOperations name="getInfoStruct" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//DataStruct"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSetTerm" eSuperTypes="#//FileTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessMode" lowerBound="1"
        eType="#//AccessMode" defaultValueLiteral="I">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Imposta il tipo di accesso al data set."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalMember" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyedAccess" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Imposta il tipo di accesso al data set."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Display" abstract="true" interface="true">
    <eTypeParameters name="D">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="chain">
      <eParameters name="format" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain">
      <eParameters name="format" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="close"/>
    <eOperations name="close">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="get" lowerBound="1">
      <eGenericType eTypeParameter="#//Display/D"/>
    </eOperations>
    <eOperations name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="open"/>
    <eOperations name="open">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="readc">
      <eParameters name="format" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="show">
      <eParameters name="format" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="update">
      <eParameters name="format" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="write">
      <eParameters name="format" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayTerm" eSuperTypes="#//FileTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileTerm" abstract="true" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//term/Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="format" containment="true">
      <eGenericType eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//term/DataTerm">
        <eTypeArguments eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//def/CompoundDataDef">
          <eTypeArguments/>
          <eTypeArguments eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//term/DataTerm">
            <eTypeArguments/>
          </eTypeArguments>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infoStruct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userOpen" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Imposta il tipo di accesso al data set."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="KeyList" instanceTypeName="Object[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyListTerm" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//term/Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyFields" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KSDataSet" abstract="true" interface="true">
    <eTypeParameters name="R">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
    </eTypeParameters>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="delete">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="delete">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="reade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="endOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="readpe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="beginningOfData" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Data"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="keyList" lowerBound="1" eType="#//KeyList"/>
      <eParameters name="found" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//DataSet">
      <eTypeArguments eTypeParameter="#//KSDataSet/R"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index" abstract="true" interface="true">
    <eOperations name="getColumns" upperBound="-1" eType="#//IndexColumn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexColumn" abstract="true" interface="true">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getDirection" lowerBound="1" eType="#//OperationDirection"/>
    <eOperations name="getLength" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="isNumeric" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Print" abstract="true" interface="true">
    <eTypeParameters name="D">
      <eBounds eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="close"/>
    <eOperations name="close">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="open"/>
    <eOperations name="open">
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="get" lowerBound="1">
      <eGenericType eTypeParameter="#//Print/D"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrintTerm" eSuperTypes="#//FileTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="RRDataSet" abstract="true" interface="true">
    <eTypeParameters name="R">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
    </eTypeParameters>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="lock" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="chain" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setgt">
      <eTypeParameters name="E">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      </eTypeParameters>
      <eParameters name="keyField" lowerBound="1">
        <eGenericType eTypeParameter="#//RRDataSet/setgt.6/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setll">
      <eTypeParameters name="E">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      </eTypeParameters>
      <eParameters name="keyField" lowerBound="1">
        <eGenericType eTypeParameter="#//RRDataSet/setll.1/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="keyField" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Numeric"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eOperations name="setll">
      <eParameters name="relativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="notFound" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="equal" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
      <eParameters name="error" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Indicator"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="#//DataSet">
      <eTypeArguments eTypeParameter="#//RRDataSet/R"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMDataSet" abstract="true" interface="true">
    <eTypeParameters name="R">
      <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-data.ecore#//Record"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//RRDataSet">
      <eTypeArguments eTypeParameter="#//SMDataSet/R"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationDirection">
    <eLiterals name="Forward" value="10" literal="F"/>
    <eLiterals name="Backward" value="20" literal="B"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationSet">
    <eLiterals name="Chain" value="10" literal="CHAIN"/>
    <eLiterals name="SetLowerLimit" value="20" literal="SETLL"/>
    <eLiterals name="SetGreaterThan" value="30" literal="SETGT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationRead">
    <eLiterals name="Chain" value="10" literal="CHAIN"/>
    <eLiterals name="Read" value="20" literal="READ"/>
    <eLiterals name="ReadEqual" value="30" literal="READE"/>
    <eLiterals name="ReadPrior" value="40" literal="READP"/>
    <eLiterals name="ReadPriorEqual" value="50" literal="READPE"/>
  </eClassifiers>
</ecore:EPackage>
