<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://www.smeup.org/asup/os/core" nsPrefix="os-core">
  <eClassifiers xsi:type="ecore:EClass" name="CreationInfo" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationUser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationSystem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionManager" abstract="true" interface="true">
    <eOperations name="prepareException" eType="#//MessageException">
      <eTypeParameters name="E">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      </eTypeParameters>
      <eParameters name="job" eType="#//jobs/Job"/>
      <eParameters name="message" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
    </eOperations>
    <eOperations name="prepareException" eType="#//MessageException">
      <eTypeParameters name="E">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      </eTypeParameters>
      <eParameters name="job" eType="#//jobs/Job"/>
      <eParameters name="message" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      <eParameters name="variable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="prepareException" eType="#//MessageException">
      <eTypeParameters name="E">
        <eBounds eClassifier="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      </eTypeParameters>
      <eParameters name="job" eType="#//jobs/Job"/>
      <eParameters name="message" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.mi.core/model/mi-core.ecore#//JavaEnum"/>
      <eParameters name="variables" lowerBound="1" eType="#//MessageVariableList"/>
    </eOperations>
    <eOperations name="prepareException" eType="#//MessageException">
      <eParameters name="job" eType="#//jobs/Job"/>
      <eParameters name="message" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="messageFileName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="messageFileLib" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="variables" lowerBound="1" eType="#//MessageVariableList"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MessageVariableList" instanceClassName="java.lang.Object[]"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MessageException" instanceClassName="org.smeup.sys.os.core.OperatingSystemMessageException"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider">
    <eOperations name="getAvailableProcessors" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/DecimalDef">
        <details key="precision" value="10"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getLoadAverage" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/DecimalDef">
        <details key="precision" value="10"/>
        <details key="scale" value="2"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/Context"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creationInfo" eType="#//CreationInfo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="installPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Path di installazione del sistema.&#xA;&#xA;All'interno e' generalmente prevista una strutturazione del tipo:&#xA;&#xA;$installPath/library/objectType/objectName"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastJobNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//SystemStatus" defaultValueLiteral="STP"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemLibrary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemUser" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temporaryLibrary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableContainer" eType="#//env/EnvironmentVariableContainer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//System"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SystemEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SystemEventType">
    <eLiterals name="Starting" value="10" literal="STARTING"/>
    <eLiterals name="Started" value="20" literal="STARTED"/>
    <eLiterals name="StatusChanged" value="30" literal="STATUS_CHG"/>
    <eLiterals name="Stopping" value="40" literal="STOPPING"/>
    <eLiterals name="Stopped" value="50" literal="STOPPED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemListener" abstract="true" interface="true">
    <eOperations name="handleEvent">
      <eParameters name="event" lowerBound="1" eType="#//SystemEvent"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemManager" abstract="true" interface="true">
    <eOperations name="start" lowerBound="1" eType="#//jobs/Job">
      <eParameters name="system" lowerBound="1" eType="#//System"/>
    </eOperations>
    <eOperations name="stop"/>
    <eOperations name="registerListener">
      <eParameters name="listener" lowerBound="1" eType="#//SystemListener"/>
    </eOperations>
    <eOperations name="updateStatus">
      <eParameters name="status" lowerBound="1" eType="#//SystemStatus"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SystemStatus">
    <eLiterals name="Activating" value="10" literal="ACT"/>
    <eLiterals name="Started" value="20" literal="STR"/>
    <eLiterals name="Ending" value="70" literal="END"/>
    <eLiterals name="Stopped" value="80" literal="STP"/>
  </eClassifiers>
  <eSubpackages name="jobs" nsURI="http://www.smeup.org/asup/os/core/jobs" nsPrefix="os-core-jobs">
    <eClassifiers xsi:type="ecore:EClass" name="Job" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/ContextProvider">
      <eOperations name="getJobStatus" lowerBound="1" eType="#//jobs/JobStatus">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="20"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getCPUUsage" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/DecimalDef">
          <details key="precision" value="10"/>
          <details key="scale" value="2"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getMemorySize" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/DecimalDef">
          <details key="precision" value="10"/>
          <details key="scale" value="0"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getPriority" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="10"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="isActive" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="10"/>
        </eAnnotations>
      </eOperations>
      <eOperations name="isRouted" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="10"/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/Context"
          transient="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="creationInfo" eType="#//CreationInfo"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentLibrary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="QGPL">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="10"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" eType="ecore:EEnum ../../org.smeup.sys.il.core/model/il-data.ecore#//def/DateFormat"
          defaultValueLiteral="*DMY"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateSeparator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="/">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="1"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobID" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="13"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jobReference" lowerBound="1"
          eType="#//jobs/JobReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jobRunInfo" lowerBound="1"
          eType="#//jobs/JobRunInfo" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jobThread" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//Thread"
          transient="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobType" eType="#//jobs/JobType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="libraries" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messages" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="switches" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="00000000">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="8"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="system" lowerBound="1"
          eType="#//System" transient="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeSeparator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=":">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="1"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variableContainer" eType="#//env/EnvironmentVariableContainer"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobCapability" abstract="true" interface="true">
      <eOperations name="getJobReference" lowerBound="1" eType="#//jobs/JobReference"/>
      <eOperations name="getPort" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/Capability">
        <eTypeArguments eClassifier="#//jobs/Job"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobEvent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//jobs/Job"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//jobs/JobEventType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="JobEventType">
      <eLiterals name="Starting" value="10" literal="STARTING"/>
      <eLiterals name="Started" value="20" literal="STARTED"/>
      <eLiterals name="StatusChanged" value="30" literal="STATUS_CHG"/>
      <eLiterals name="Stopping" value="40" literal="STOPPING"/>
      <eLiterals name="Stopped" value="50" literal="STOPPED"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobListener" abstract="true" interface="true">
      <eOperations name="handleEvent">
        <eParameters name="event" lowerBound="1" eType="#//jobs/JobEvent"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobLog" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" lowerBound="1"
          upperBound="-1" eType="#//jobs/JobLogEntry" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="job" lowerBound="1" eType="#//jobs/Job"
          transient="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobLogEntry" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="128"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobLogManager" abstract="true" interface="true">
      <eOperations name="addEntry">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="gravity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="info">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="warning">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="message" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="error">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/JobLog">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/JobLog">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="jobReference" lowerBound="1" eType="#//jobs/JobReference"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/JobLog">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="number" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobManager" abstract="true" interface="true">
      <eOperations name="close" eType="#//jobs/Job">
        <eParameters name="capability" lowerBound="1" eType="#//jobs/JobCapability"/>
      </eOperations>
      <eOperations name="close">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
      </eOperations>
      <eOperations name="create" lowerBound="1" eType="#//jobs/JobCapability">
        <eParameters name="identity" lowerBound="1">
          <eGenericType eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/Identity">
            <eTypeArguments/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="create" lowerBound="1" eType="#//jobs/JobCapability">
        <eParameters name="identity" lowerBound="1">
          <eGenericType eClassifier="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//ctx/Identity">
            <eTypeArguments/>
          </eGenericType>
        </eParameters>
        <eParameters name="jobName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="spawn" lowerBound="1" eType="#//jobs/JobCapability">
        <eParameters name="parent" lowerBound="1" eType="#//jobs/Job"/>
      </eOperations>
      <eOperations name="spawn" lowerBound="1" eType="#//jobs/JobCapability">
        <eParameters name="parent" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="jobName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="delay">
        <eParameters name="millis" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="delay">
        <eParameters name="resumeTime" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getActiveJobs" lowerBound="1" upperBound="-1" eType="#//jobs/Job"/>
      <eOperations name="lookup" eType="#//jobs/Job">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="jobReference" lowerBound="1" eType="#//jobs/JobReference"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/Job">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="number" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/Job">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="number" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="lookupActiveJob" eType="#//jobs/Job">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="jobID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/Job">
        <eParameters name="capability" lowerBound="1" eType="#//jobs/JobCapability"/>
      </eOperations>
      <eOperations name="lookup" eType="#//jobs/Job">
        <eParameters name="contextID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="registerListener">
        <eParameters name="listener" lowerBound="1" eType="#//jobs/JobListener"/>
      </eOperations>
      <eOperations name="registerWriter">
        <eParameters name="capability" lowerBound="1" eType="#//jobs/JobCapability"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="writer" lowerBound="1" eType="ecore:EClass ../../org.smeup.sys.il.core/model/il-core.ecore#//out/ObjectWriter"/>
      </eOperations>
      <eOperations name="setDefaultWriter">
        <eParameters name="capability" lowerBound="1" eType="#//jobs/JobCapability"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="updateStatus">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="status" lowerBound="1" eType="#//jobs/JobStatus"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobReference" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobNumber" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/DecimalDef">
          <details key="precision" value="6"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobUser" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="10"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="10"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobRunInfo" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memorySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="JobStatus">
      <eLiterals name="Active" value="10" literal="ACT"/>
      <eLiterals name="TimeWaiting" value="20" literal="TIMW"/>
      <eLiterals name="Run" value="30" literal="RUN"/>
      <eLiterals name="MessageWaiting" value="40" literal="MSGW"/>
      <eLiterals name="LockWaiting" value="50" literal="LCKW"/>
      <eLiterals name="EventWaiting" value="60" literal="EVTW"/>
      <eLiterals name="Hold" value="70" literal="HLD"/>
      <eLiterals name="EndOfJob" value="80" literal="EOJ"/>
      <eLiterals name="End" value="90" literal="END"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="JobType">
      <eLiterals name="Kernel" value="10" literal="KRN"/>
      <eLiterals name="Interactive" value="20" literal="INT"/>
      <eLiterals name="Batch" value="30" literal="BCH"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="env" nsURI="http://www.smeup.org/asup/os/core/env" nsPrefix="os-core-env">
    <eClassifiers xsi:type="ecore:EEnum" name="EnvironmentLevel">
      <eLiterals name="System" value="10" literal="*SYS"/>
      <eLiterals name="Job" value="20" literal="*JOB"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentVariable" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="20"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="il-data" references="../../org.smeup.sys.il.core/model/il-data.ecore#//def/CharacterDef">
          <details key="length" value="132"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentVariableContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//env/EnvironmentVariable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentVariableManager">
      <eOperations name="addVariable" eType="#//env/EnvironmentVariable">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="level" lowerBound="1" eType="#//env/EnvironmentLevel"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="replace" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eOperations>
      <eOperations name="changeVariable" eType="#//env/EnvironmentVariable">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="level" lowerBound="1" eType="#//env/EnvironmentLevel"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="listVariables" upperBound="-1" eType="#//env/EnvironmentVariable">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="level" lowerBound="1" eType="#//env/EnvironmentLevel"/>
      </eOperations>
      <eOperations name="lookupVariable" eType="#//env/EnvironmentVariable">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="level" lowerBound="1" eType="#//env/EnvironmentLevel"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="removeVariable" eType="#//env/EnvironmentVariable">
        <eParameters name="job" lowerBound="1" eType="#//jobs/Job"/>
        <eParameters name="level" lowerBound="1" eType="#//env/EnvironmentLevel"/>
        <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
