<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="http://www.smeup.org/asup/il/memo/test" nsPrefix="il-memo-test">
  <eClassifiers xsi:type="ecore:EClass" name="ObjectA" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//ObjectNameable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectB" lowerBound="1"
        eType="#//ObjectB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectB" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enum1" lowerBound="1" eType="#//Enum1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Enum1">
    <eLiterals name="Value1" value="10" literal="VAL1"/>
    <eLiterals name="Value2" value="20" literal="VAL2"/>
  </eClassifiers>
</ecore:EPackage>
