<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="store" nsURI="http://www.smeup.org/asup/il/memo/cdo/store" nsPrefix="il-memo-cdo-store">
  <eClassifiers xsi:type="ecore:EClass" name="CDOStoreConfig" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adapter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="credentials" lowerBound="1"
        eType="ecore:EClass ../../org.smeup.sys.db.core/model/db-core.ecore#//ConnectionCredentials"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driver" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repository" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socketConfig" lowerBound="1"
        eType="ecore:EClass ../../org.smeup.sys.co.core/model/co-core.ecore#//ServerSocketConfig"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
