<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://www.smeup.org/asup/dk/core" nsPrefix="dk-core">
  <eClassifiers xsi:type="ecore:EClass" name="DevelopmentStatus" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//meta/Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="#//DevelopmentStatusType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DevelopmentStatusType">
    <eLiterals name="Supported" value="10" literal="SUP"/>
    <eLiterals name="Unsupported" value="20" literal="UNS"/>
    <eLiterals name="ToDo" value="30" literal="TODO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="../../org.smeup.sys.il.core/model/il-core.ecore#//meta/Facet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
